FROM node:20-alpine AS development

WORKDIR /EMS/Client/

COPY package.json .
COPY package-lock.json .

RUN npm i


COPY . .


EXPOSE 3000


CMD [ "npm" , "run" , "dev" ]

FROM node:20-alpine AS production

WORKDIR /EMS/Client/

COPY package.json .
COPY package-lock.json .

RUN npm i --production


COPY . .


EXPOSE 3000

RUN npm run build


CMD [ "npm" , "run" , "start" ]